#!/bin/bash

set -e
set -u

THIS_DIR="$(dirname $(realpath ${BASH_SOURCE[0]}))"
cd $THIS_DIR

. common_make_packages.sh

RENODE_ROOT_DIR=$THIS_DIR/../..
OUTPUT_DIR=$RENODE_ROOT_DIR/output/bin/$TARGET
DESTINATION=$RENODE_ROOT_DIR/output/bin/Portable
RENODE_BIN=$OUTPUT_DIR/Renode.exe
MONO_VERSION=4.5

mkdir -p $DESTINATION
rm -rf $DESTINATION/*

echo ">>> Preparing dlls config..."

CONFIG_FILE=`mktemp config--XXXXXX`
cat /etc/mono/config > $CONFIG_FILE
sed -e 's/$mono_libdir\///g' -i $CONFIG_FILE

# TODO: this seems to be necessary, otherwise Renode crashes on opening tlib.so in docker
echo '<dllmap dll="i:dl">' >> $CONFIG_FILE
echo '  <dllentry dll="__Internal" name="dlopen" target="dlopen"/>' >> $CONFIG_FILE
echo '</dllmap>' >> $CONFIG_FILE

echo ">>> Generating bundle..."

ln -sf $OUTPUT_DIR/LZ4.dll LZ4cc.dll
ln -sf $OUTPUT_DIR/LZ4.dll LZ4mm.dll
ln -sf $OUTPUT_DIR/LZ4.dll LZ4pn.dll

# this one might crash, we will re-compile it
set +e
mkbundle \
    --simple \
    --custom \
    --machine-config /etc/mono/$MONO_VERSION/machine.config \
    --config $CONFIG_FILE \
    -L $OUTPUT_DIR \
    -L /usr/lib/cli/atk-sharp-2.0 \
    -L /usr/lib/cli/glib-sharp-2.0 \
    -L /usr/lib/cli/gdk-sharp-2.0 \
    -L /usr/lib/cli/pango-sharp-2.0 \
    -L /usr/lib/cli/gtk-sharp-2.0 \
    -L /usr/lib/mono/$MONO_VERSION \
    -z --static --keeptemp --nomain \
    $RENODE_BIN 2>/dev/null
set -e

echo ">>> Re-compiling bundle..."

WRAPPER_SOURCE_FILE=`mktemp bundler--XXXXXX.c`

echo "extern int mono_environment_exitcode_get();" > $WRAPPER_SOURCE_FILE
echo "extern void mono_aot_register_module();" >> $WRAPPER_SOURCE_FILE

# this file is generated by `mkbundle`
cat $THIS_DIR/temp.c >> $WRAPPER_SOURCE_FILE

# this file is proveded by us
cat $THIS_DIR/linux_portable/additional.c >> $WRAPPER_SOURCE_FILE

gcc \
    -Wl,--wrap=powf  \
    -Wl,--wrap=logf  \
    -Wl,--wrap=expf  \
    -Wl,--wrap=getrandom  \
    -fvisibility=hidden \
    -Wl,--export-dynamic \
    $WRAPPER_SOURCE_FILE  \
    -I/usr/include/mono-2.0  \
    $THIS_DIR/temp.s  \
    -lm  \
    -ldl  \
    -lz `pkg-config --libs-only-L mono-2`  \
    -Wl,-Bstatic  \
    -lmono-2.0  \
    -Wl,-Bdynamic `pkg-config --libs-only-l mono-2 | sed -e "s/\-lmono-2.0 //"`  \
    -static-libgcc -static-libstdc++ \
    -o $DESTINATION/Renode

echo ">>> Copying dependencies..."

cp $OUTPUT_DIR/cores-*.dll $DESTINATION
cp $OUTPUT_DIR/Renode-peripherals.dll $DESTINATION

cp /usr/lib/libMonoPosixHelper.so $DESTINATION
cp /usr/lib/libmono-btls-shared.so $DESTINATION

cp $RENODE_ROOT_DIR/.renode-root $DESTINATION
cp -r $RENODE_ROOT_DIR/scripts $DESTINATION
cp -r $RENODE_ROOT_DIR/platforms $DESTINATION

echo ">>> Cleaning up..."

rm temp.c
rm temp.o
rm temp.s
rm $WRAPPER_SOURCE_FILE
rm $CONFIG_FILE
rm LZ4cc.dll
rm LZ4mm.dll
rm LZ4pn.dll

echo ">>> Creating renode_portable.tar..."
tar -cf ../../output/packages/renode-$VERSION-portable.tar --transform='s/output\/bin\/Portable/renode_portable/' $DESTINATION

echo "Created a portable package in output/packages/renode-$VERSION-portable.tar"
